# Generated by Django 6.1.2 on 2026-10-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('check_number', models.CharField(max_length=100, verbose_name='Номер счета')),
                ('money', models.IntegerField(max_length=100, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
